spring.application.name=cafetinapp
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/cafetinapp
spring.datasource.username=cafetinuser
spring.datasource.password=cafetinpass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

sprindoc.swagger-ui.path=/swagger-ui.html
springdoc.api.docs.path=/api-docs